### ISSUE TITLE
Obtengo este error al descargar recursos con la última versión disponible... Existe algún parametro mediante linea de comando para indicarle que no genere las cookies mediante ytdlp? probé generando las cookies desde el navegador y funciona para el video exacto donde genero este error ytdlp

### ISSUE THREAD

**Issue by eber05** [ivansaul/codigo_facilito_downloader#12]
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "downloader.py", line 140, in <module>
    dl.dl_course()
  File "downloader.py", line 52, in dl_course
    self.m3u8_downloader(file_name=f'{m}-{title}', url=url, dest=dest, ext_dwl=self.external_downloader)
  File "downloader.py", line 31, in m3u8_downloader
    subprocess.run(command, check=True)
  File "C:\Users\EBER\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['yt-dlp', '--cookies', 'cookies.txt', '-o', 'tmp/modulo_2/9-Crear links simbólicos.%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-s 10 -x 10 -k 1M', 'https://video-storage.codigofacilito.com/hls/365/11892/playlist.m3u8']' returned non-zero exit status 1.

**Comment by eber05** [comment]
Lo resolví provisionalmente creando un bucle en el método `main(d,q)` del archivo `downloader.py`
Estas son las adaptaciones de código que hice:
``` python
@click.command()
@click.option('-d', type=click.Choice(downloaders), default='aria2', prompt=False, help=help_d)
@click.option('-q', type=click.Choice(qualities), default='best', prompt=False, help=help_q)
def main(d, q):
    error=True
    while error:
        try:
            utils.check_aria2()
            print("Bypass utils.check_aria2 1\n")
            FacilitoCookies().get_cookies()
            print("Bypass getcookies 1")
            dl = Downloader(external_downloader=d, quality=q)
            print("Bypass downloader select and quality 1")
            dl.load_data()
            print("Bypass load data 1")
            error = False
            dl.dl_course()
            print("Bypass download course 1")
        except:
            print("\n--------------REINTENTANDO--------------\n")
            error=True
    print("Salí del bucle de errores")
```
