### ISSUE TITLE
Error al descargar videos

### ISSUE THREAD

**Issue by mvasquezn** [ivansaul/codigo_facilito_downloader#22]
Realice la instalacion en Windows, y obtengo un error al descargar los videos 

`[1 / 1][streaming] Clase Completa
[generic] Extracting URL: https://video-storage.codigofacilito.com/hls/746/16413/playlist.m3u8 
[generic] playlist: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\codigo_facilito_downloader\downloader.py", line 82, in <module>
    main()
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Documents\python_projects\codigo_facilito_downloader\downloader.py", line 79, in main
    dl.dl_course()
  File "C:\Users\Documents\python_projects\codigo_facilito_downloader\downloader.py", line 58, in dl_course
    self.m3u8_downloader(file_path = file_path, url=url, ext_dwl=self.external_downloader)
  File "C:\codigo_facilito_downloader\downloader.py", line 38, in m3u8_downloader
    subprocess.run(command, check=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yt-dlp', '-f', 'bv[height<=1080]+ba/b[height<=1080]', '--cookies', 'cookies_copy.txt', '-o', 'Qué hace un Científico de Datos - Generación 3 - Bootcamp de Ciencia de Datos/1. Qué hace un Científico de Datos/1. Clase Completa.%(ext)s', '-N', '10', 'https://video-storage.codigofacilito.com/hls/746/16413/playlist.m3u8']' returned non-zero exit status 1.
`

Actualmente lo hago desde un entorno virtual con Python 3.10 pero tambien lo he intentado con la 3.11 y cambiando las cookies pero no obtengo ningun resultado

**Comment by ivansaul** [comment]
@mvasquezn estas copiando mal las cookies. Debe ser desde un video cualquiera.
como por ejemplo `https://codigofacilito.com/videos/1-intro ...` y finalmente descargas con `python downloader.py`

**Comment by mvasquezn** [comment]
Listo, ya se resolvio. Gracias
