### ISSUE TITLE
Problemas al generar data.json en algunos casos

### ISSUE THREAD

**Issue by floxcristian** [ivansaul/codigo_facilito_downloader#27]
Ocurre error a la hora de generar el data.json, supongo que será por algunos caracteres no soportados.

Ejemplo: https://codigofacilito.com/cursos/bootcamp-cloud-fundamentos?play=true

Error: 

`Traceback (most recent call last):
  File "C:\Users\Master\Desktop\repositorios\codigo_facilito_downloader\facilito.py", line 145, in <module>
    facilito.get_m3u8_url()
  File "C:\Users\Master\Desktop\repositorios\codigo_facilito_downloader\facilito.py", line 113, in get_m3u8_url
    print(f'[{j} / {k}][streaming] {video_title}')
  File "C:\Users\Master\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 23: character maps to <undefined>`

**Comment by ivansaul** [comment]
@floxcristian si eres usuario de windows, cambia de terminal. Prueba con la terminal de git (gitbash).

**Comment by floxcristian** [comment]
Estoy usando gitbash. Y el error ocurre en ese link en específico. Todos los demás funcionan bien.

**Comment by ivansaul** [comment]
@floxcristian ese error es propio de windows. De todos modos lo revisare. Intenta actualizando gitbash, o prueba con otras terminales cmd, powershell. Otra alternativa usar `codespaces` modificando esta linea a `headless = true`
https://github.com/ivansaul/codigo_facilito_downloader/blob/140b28f8b7768b68b18bedee6359e5e812632a6b/facilito.py#L6
